version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: OVFHE56vz8BH9F0NZ9aA1zSXBB7tYRsO
      POSTGRES_DB: socia_network
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    command: ["./main"]
    stdin_open: true
    tty: true

volumes:
  db-data:
